FROM python:3.10

WORKDIR /frontend
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.headless=true"]