FROM python:3.10

WORKDIR /backend
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN ls /backend
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]